-- Création Base de données
CREATE DATABASE Jeux_video
GO

USE Jeux_video
GO

-- Création de la table utilisateur
CREATE TABLE UTILISATEUR
(
	Util_ID INT IDENTITY(1,1),
	Pseudo VARCHAR(38)NOT NULL,
	Mdp VARCHAR(38)NOT NULL,
	CONSTRAINT PK_Utilisateur PRIMARY KEY(Util_ID)
)
-- Création de la table console
CREATE TABLE CONSOLE
(
	Cons_ID INT IDENTITY(1,1),
	Nom VARCHAR(38) NOT NULL,
	CONSTRAINT PK_Console PRIMARY KEY(Cons_ID)
	)
-- Création de la table genre
CREATE TABLE GENRE
(
	Gen_ID INT IDENTITY(1,1),
	Libelle VARCHAR(38) NOT NULL,
	CONSTRAINT PK_Genre PRIMARY KEY(Gen_ID)
)
-- Création de la table JeuxVideo
CREATE TABLE JEUXVIDEO
(
	JV_ID INT IDENTITY(1,1),
	Titre VARCHAR(38) NOT NULL,
	Editeur VARCHAR(38) NOT NULL,
	Genre INT NOT NULL,
	CONSTRAINT PK_JeuxVideo PRIMARY KEY(JV_ID),
	CONSTRAINT FK_JeuxVideo_Genre FOREIGN KEY(Genre) REFERENCES GENRE(Gen_ID)
	)
-- Création de la table Appartenir
CREATE TABLE APPARTENIR
(
	JV_ID INT,
	Cons_ID INT,
	CONSTRAINT PK_APPARTENIR PRIMARY KEY (JV_ID ,Cons_ID),
	CONSTRAINT FK_APPARTENIR_JEUXVIDEO FOREIGN KEY (JV_ID) REFERENCES JEUXVIDEO (JV_ID),
	CONSTRAINT FK_APPARTENIR_CONSOLE FOREIGN KEY(Cons_ID) REFERENCES CONSOLE (Cons_ID)
	)
-- Création de la table Ajouter
CREATE TABLE AJOUTER
(
	JV_ID INT,
	Util_ID INT,
	CONSTRAINT PK_AJOUTER PRIMARY KEY (JV_ID , Util_ID),
	CONSTRAINT FK_AJOUTER_JEUXVIDEO FOREIGN KEY (JV_ID) REFERENCES JEUXVIDEO (JV_ID),
	CONSTRAINT FK_AJOUTER_UTILISATEUR FOREIGN KEY (Util_ID) REFERENCES UTILISATEUR (Util_ID)
	)
-- Création de la table Noter
CREATE TABLE Noter
(
	JV_ID INT,
	Util_ID INT,
	Note CHAR(2),
	CONSTRAINT PK_NOTER PRIMARY KEY (JV_ID , Util_ID),
	CONSTRAINT FK_NOTER_JEUXVIDEO FOREIGN KEY (JV_ID) REFERENCES JEUXVIDEO (JV_ID),
	CONSTRAINT FK_NOTER_UTILISATEUR FOREIGN KEY (Util_ID) REFERENCES UTILISATEUR (Util_ID)
	)


-- Jeux d'essais

INSERT INTO UTILISATEUR(Pseudo, Mdp) VALUES ('Aymericorato','1234')
INSERT INTO UTILISATEUR(Pseudo, Mdp) VALUES ('Rakbaal','4567')

